### ISSUE TITLE
No docker plugin defined

### ISSUE THREAD

**Issue by hferentschik** [redhat-helloworld-msa/aloha#4]
The README says to build and deploy like so:

```
mvn clean package docker:build fabric8:json fabric8:apply
```

However, the _pom.xml_ does not define the docker plugin. Hence then trying to use the above command I get:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.691 s
[INFO] Finished at: 2016-04-22T21:35:15+02:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'docker' in the current project and in the     plugin groups [org.jboss.maven.plugins, org.apache.maven.plugins, org.codehaus.    mojo] available from the repositories [local (/Users/hardy/tmp/m2), jboss-public-    repository-group (https://repository.jboss.org/nexus/content/groups/public/),     central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read     the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/    NoPluginFoundForPrefixException    
```

**Comment by rafabene** [comment]
That's odd because the docker plugin is defined here: https://github.com/redhat-helloworld-msa/aloha/blob/master/pom.xml#L181-L183

Based on this issue https://github.com/fabric8io/fabric8/issues/3298 , I'm wondering if the DOCKER_HOST is set according by the command `eval "$(vagrant service-manager env docker)"` according to https://github.com/redhat-helloworld-msa/helloworld-msa/blob/master/prepare-cdk.adoc

**Comment by rafabene** [comment]
any tips on this issue @rhuss ?

**Comment by rhuss** [comment]
sorry, can't reproduce it.  @hferentschik from which directory did you called Maven ?

**Comment by hferentschik** [comment]
> sorry, can't reproduce it.

Not me either anymore ;-) I was not in sync with master and had an outdated version of the pom. Doh.
